name: 'Lint and test'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test -- -c -R base -t10
    - name: Test basic CLI functionality
      run: sh test/test-cli.sh
    - name: Lint
      run: npm run lint
